import { execFileSync } from 'node:child_process'
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
if (!process.env.npm_execpath) throw new Error('Run this script through pnpm build.')
const [tree] = JSON.parse(
  execFileSync(
    process.execPath,
    [process.env.npm_execpath, 'list', '--prod', '--depth', 'Infinity', '--json'],
    { encoding: 'utf8' },
  ),
)
const packages = new Map()
function visit(dependencies) {
  for (const pkg of Object.values(dependencies ?? {})) {
    packages.set(`${pkg.from}@${pkg.version}`, pkg)
    // A later occurrence may expand dependencies omitted by an earlier dedupe.
    visit(pkg.dependencies)
  }
}
visit(tree.dependencies)
const notices = [
  'Third-party notices for GraphWAN web dependencies.\nGenerated by pnpm build; do not edit by hand.\n',
]
for (const [name, pkg] of [...packages.entries()].sort(([a], [b]) => a.localeCompare(b, 'en'))) {
  const licenses = readdirSync(pkg.path)
    .filter((name) => /^(licen[sc]e|copying|notice)([.-].*)?$/i.test(name))
    .sort()
  if (!licenses.length) throw new Error(`Missing license notice for ${name}`)
  notices.push(`${'='.repeat(72)}\n${name}\n${'='.repeat(72)}\n`)
  for (const file of licenses)
    notices.push(`${readFileSync(join(pkg.path, file), 'utf8').trim()}\n`)
}
writeFileSync('../internal/webui/dist/THIRD_PARTY_LICENSES.txt', notices.join('\n'))
console.log(`Preserved license notices for ${packages.size} web dependencies.`)
